name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Archive artifacts (PRD)
        uses: actions/upload-artifact@v2
        with:
          name: rmg-${{ env.RMG_VER }}
          path: |
            PRD

      - name: Archive artifacts (UAT)
        uses: actions/upload-artifact@v2
        with:
          name: rmg-${{ env.RMG_VER }}-UAT
          path: |
            UAT