name: Build 2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i

      - name: Clone UAT repo
        run: git clone --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/${{ env.UAT_REPO_NAME }}.git

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
