name: Release to BitBucket

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator

    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: rmg-${{ github.event.inputs.version }}-UAT

      - name: Display structure
        run: |
          ls -R