name: Release to BitBucket

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator

    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/wongchito/RailMapGenerator/actions/artifacts | node ./parse-artifact-list.js ${{ github.event.inputs.version }} UAT
#          echo "ARTIFACT_URL=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/wongchito/RailMapGenerator/actions/artifacts | node ./parse-artifact-list.js ${{ github.event.inputs.version }} UAT)" >> $GITHUB_ENV
#          curl -H "Accept: application/vnd.github.v3+json" ${{ env.ARTIFACT_URL }}

      - name: Display structure
        run: |
          ls -R